spring.application.name=order-cart-service

spring.data.mongodb.uri=mongodb://localhost:27017/orderdb

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8081
eureka.client.enabled=false