spring.application.name=order-cart-service

spring.data.mongodb.uri=mongodb://localhost:27017/orderdb

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8081
eureka.client.enabled=false

# Resilience4j Configuration
resilience4j.retry.instances.paymentService.maxAttempts=3
resilience4j.retry.instances.paymentService.waitDuration=2s
resilience4j.retry.instances.paymentService.ignoreExceptions=com.facile.order_cart_service.order.saga.exception.PaymentVerificationException

resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=10

resilience4j.retry.instances.inventoryService.maxAttempts=3
resilience4j.retry.instances.inventoryService.waitDuration=2s
resilience4j.retry.instances.inventoryService.ignoreExceptions=com.facile.order_cart_service.order.saga.exception.InventoryException

resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.inventoryService.slidingWindowSize=10